# GitLab CI/CD configuration for AAA4J-RADIUS
stages:
  - validate
  - test
  - build
  - package
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

# Cache Maven dependencies
cache:
  paths:
    - .m2/repository

# Validate stage - check code quality
validate:
  stage: validate
  image: maven:3.8.6-openjdk-9
  script:
    - mvn $MAVEN_CLI_OPTS validate
    - mvn $MAVEN_CLI_OPTS checkstyle:check
    - mvn $MAVEN_CLI_OPTS spotbugs:check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Test stage - run unit tests
test:
  stage: test
  image: maven:3.8.6-openjdk-9
  script:
    - mvn $MAVEN_CLI_OPTS test
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    reports:
      junit: 
        - "*/target/surefire-reports/TEST-*.xml"
    paths:
      - "*/target/surefire-reports/"
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Build stage - compile and package
build:
  stage: build
  image: maven:3.8.6-openjdk-9
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
  artifacts:
    paths:
      - "*/target/classes/"
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Package stage - create JAR files
package:
  stage: package
  image: maven:3.8.6-openjdk-9
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests
  artifacts:
    paths:
      - "*/target/*.jar"
      - "*/target/*.war"
    expire_in: 1 month
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Deploy to GitLab Package Registry (for snapshots)
deploy-snapshot:
  stage: deploy
  image: maven:3.8.6-openjdk-9
  script:
    - echo "Deploying snapshot to GitLab Package Registry"
    - mvn $MAVEN_CLI_OPTS deploy -DskipTests
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  environment:
    name: gitlab-package-registry
  only:
    - master

# Deploy to Maven Central (for releases)
deploy-release:
  stage: deploy
  image: maven:3.8.6-openjdk-9
  script:
    - echo "Deploying release to Maven Central"
    - mvn $MAVEN_CLI_OPTS deploy -DskipTests
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
  environment:
    name: maven-central
  only:
    - tags

# Security scan
security-scan:
  stage: test
  image: maven:3.8.6-openjdk-9
  script:
    - mvn $MAVEN_CLI_OPTS org.owasp:dependency-check-maven:check
  artifacts:
    reports:
      dependency_scanning: "*/target/dependency-check-report.xml"
    paths:
      - "*/target/dependency-check-report.html"
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  allow_failure: true 